name: frontendDocker

# main branch에 push 되면 실행
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./asset-management
jobs:

  Docker:
    name: DockerImageBuildandPush (CI)
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Login DockHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}


      - name: Docker build
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/assets .

      - name: Docker Push Reigistry
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/assets .

