name: frontendCI

# main branch에 push 되면 실행
on:
  push:
    branches:
      - main

jobs:
  buildAndTest:
    name: Ci pipeline
    runs-on: ubuntu-latest
    strategy:
    # Node version은 18 버전을 이용한다.
      matrix:
        node-version: ['18.x']
    steps:
      - uses: actions/checkout@v3

      # Initialize Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      # Install project dependencies and Build project
      - name: Install dependencies and build
        run: |
          cd asset-management
          yarn
          yarn build
        env:
          CI: ""
            #경고 무시
      # Test project
      - name: Testing...
        run : |
          cd asset-management
          yarn test
     